environment:
    path_to_sln: src/GitTools.Testing.sln

install:
  - choco install gitversion.portable -pre -y
  
image: Visual Studio 2017 Preview
configuration:
  - Release

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_NuGetVersion% /p:Configuration=Release
  
build_script:
  - cmd: msbuild %path_to_sln% /t:Build /p:Configuration=Release

after_build:
  - cmd: msbuild %path_to_sln% /t:Pack /p:PackageVersion=%GitVersion_NuGetVersion% /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%" /p:Configuration=Release /p:NoBuild=true
  - cmd: appveyor PushArtifact "GitTools.Testing.%GitVersion_NuGetVersion%.nupkg"

test: off
test_script:
  - cmd: cd src\GitTools.Testing.Tests
  - cmd: dotnet test --configuration Release --no-build

deploy:
  provider: NuGet
  api_key:
    secure: kyvS4pYmOCyvas5wxibDusCABHBkmORratOuw13JYeo/xj+ggCnfZhihMVUrXL7x
  skip_symbols: false
  artifact: /.*\.nupkg/

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
