install:
  - choco install gitversion.portable -pre -y

platform:
  - Any CPU

configuration:
  - Release

assembly_info:
  patch: false

before_build:
  - nuget restore src\
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src\GitTools.Testing.sln

after_build:
  - cmd: nuget pack src\GitTools.Testing\GitTools.Testing.nuspec -BasePath output\%CONFIGURATION%\ -version "%GitVersion_NuGetVersion%"
  - cmd: appveyor PushArtifact "GitTools.Testing.%GitVersion_NuGetVersion%.nupkg"
cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
