image:
  - Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

configuration:
  - Release

assembly_info:
  patch: false

before_build:
  - dotnet restore src\GitTools.Testing.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src\GitTools.Testing.sln

after_build:
  - cmd: dotnet pack src\GitTools.Testing\GitTools.Testing.csproj /p:PackageVersion="%GitVersion_NuGetVersion%" /p:NoBuild=true /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  - cmd: appveyor PushArtifact "GitTools.Testing.%GitVersion_NuGetVersion%.nupkg"
cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
